# Generated by Django 5.1.1 on 2024-10-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='last_occurrence_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
